import React,{useMemo,useEffect,useRef,useState}from'react';
import{Search,Sparkles}from'lucide-react';
import{motion}from'motion/react';
import{useAngel}from'../../context/AppContext';
import{Attachment}from'../../types';
import{AngelLogo}from'../ui/AngelLogo';
import{ChatComposer}from'./ChatComposer';
const greetings=['How was your day?','What is on your mind?','Want to talk?','What shall we figure out?','Tell me what you are working on.','Where should we start?','Anything you want to explore?','I am here. What is up?'];
export const ChatView:React.FC=()=>{const{messages,sendMessage,isChatStreaming,settings,setActiveTab}=useAngel();const light=settings.theme==='light';const[greeting]=useState(()=>greetings[Math.floor(Math.random()*greetings.length)]);const[input,setInput]=useState('');const end=useRef<HTMLDivElement>(null);useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,isChatStreaming]);const send=async(text:string,attachments:Attachment[])=>{if(!text.trim()&&!attachments.length)return;await sendMessage(text,attachments)};return <div className="flex h-full min-h-0 flex-col"><div className="flex-1 min-h-0 overflow-y-auto custom-scrollbar"><div className="mx-auto w-full max-w-4xl px-4 pb-44 pt-10 sm:px-6">{messages.length===0?<div className="flex min-h-[58vh] flex-col items-center justify-center text-center"><motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mb-7 flex h-16 w-16 items-center justify-center rounded-2xl border border-white/10 bg-white/[.035] shadow-2xl"><AngelLogo size={42} glow/></motion.div><motion.h1 initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className={`text-4xl font-semibold tracking-tight sm:text-5xl ${light?'text-slate-950':'text-white'}`}>{greeting}</motion.h1><div className="mt-6 flex flex-wrap justify-center gap-2">{['Latest tech news','Design a marketing plan','Research something for me','Help me build a project'].map(x=><button key={x} onClick={()=>setActiveTab('chat')} className={`inline-flex items-center gap-2 rounded-full border px-3.5 py-2 text-xs ${light?'border-slate-200 bg-white text-slate-600 hover:bg-slate-50':'border-white/10 bg-white/[.03] text-neutral-400 hover:bg-white/[.06]'}`}><Search className="h-3.5 w-3.5"/>{x}</button>)}</div></div>:<div className="space-y-5">{messages.map((m:any)=><div key={m.id} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==='user'?(light?'bg-slate-100 text-slate-900':'bg-white/[.08] text-white'):(light?'text-slate-800':'text-neutral-200')}`}>{m.content}</div></div>)}{isChatStreaming&&<div className="flex items-center gap-2 text-xs text-neutral-500"><Sparkles className="h-3.5 w-3.5 text-indigo-400"/>Angel is thinking...</div>}<div ref={end}/></div>}</div></div><div className="pointer-events-none fixed inset-x-0 bottom-0 z-40 px-3 pb-3 sm:px-6"><div className="pointer-events-auto mx-auto w-full max-w-4xl"><ChatComposer value={input} onChange={setInput} onSend={send} isStreaming={isChatStreaming} isLight={light} onVisual={()=>setActiveTab('visual_mode')} onVoice={()=>setActiveTab('voice')}/></div></div></div>};
