import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Home, Search, SquarePen, PanelLeftClose, PanelLeftOpen, Bot, FolderGit2, Calendar, Library, Image, MoreHorizontal, MessageSquare, ChevronRight, X, Quote } from 'lucide-react';
import { useAngel } from '../../context/AppContext';
import { NavigationTab } from '../../types';
import { AngelLogo } from '../ui/AngelLogo';
import { WindowsShortcutBadge } from '../ui/WindowsShortcutBadge';
import { UserProfileMenu } from './UserProfileMenu';
import { ChatOptionsMenu } from '../chat/ChatOptionsMenu';
import { SecretsModal } from '../modals/SecretsModal';

export const Sidebar: React.FC = () => {
  const { activeTab,setActiveTab,isSidebarCollapsed,toggleSidebar,isMobileMenuOpen,setMobileMenuOpen,conversations,activeConversationId,setActiveConversationId,createConversation,openCommandPalette,userProfile,settings,isSignedIn,setIsAuthPageOpen,isFocusMode } = useAngel();
  const isLight=settings.theme==='light';
  const [hoverExpanded,setHoverExpanded]=useState(false),[profileOpen,setProfileOpen]=useState(false),[chatOptionsId,setChatOptionsId]=useState<string|null>(null),[chatAnchor,setChatAnchor]=useState<{top:number;left:number}>(),[secretsOpen,setSecretsOpen]=useState(false);
  const expanded=!isSidebarCollapsed||hoverExpanded;
  if(isFocusMode)return null;
  const tools:Array<[string,string,React.FC<{className?:string}>,NavigationTab]>=[['agent','Agent Lab',Bot,'agent_lab'],['projects','Projects',FolderGit2,'projects'],['schedule','Schedule',Calendar,'tasks'],['library','Library',Library,'library'],['media','Media Studios',Image,'media_studio']];
  const pinned=conversations.filter(c=>c.pinned&&!c.isArchived&&!c.isSecret), archived=conversations.filter(c=>c.isArchived&&!c.isSecret), recent=conversations.filter(c=>!c.pinned&&!c.isArchived&&!c.isSecret);
  const nav=(tab:NavigationTab)=>{setActiveTab(tab);setMobileMenuOpen(false);setHoverExpanded(false)};
  const newChat=()=>{createConversation();nav('chat')};
  const openProfile=()=>isSignedIn?setProfileOpen(true):setIsAuthPageOpen(true);
  const row=(c:any)=><div key={c.id} onClick={()=>{setActiveConversationId(c.id);nav('chat')}} className={`group flex items-center gap-2 px-2.5 py-1.5 rounded-lg text-xs cursor-pointer ${activeConversationId===c.id&&activeTab==='chat'?(isLight?'bg-indigo-50 text-indigo-800':'bg-[#151926] text-white'):(isLight?'text-slate-600 hover:bg-slate-100':'text-neutral-400 hover:bg-white/5')}`}><MessageSquare className="w-3.5 h-3.5 shrink-0 text-indigo-400"/><span className="truncate flex-1">{c.title}</span><button onClick={e=>{e.stopPropagation();const r=e.currentTarget.getBoundingClientRect();setChatAnchor({top:r.top,left:r.right+8});setChatOptionsId(c.id)}} className="opacity-0 group-hover:opacity-100 p-1 rounded"><MoreHorizontal className="w-3 h-3"/></button></div>;
  const profile=<button onClick={openProfile} className={`w-full flex items-center gap-2.5 p-1.5 rounded-xl ${isLight?'hover:bg-slate-100':'hover:bg-white/5'}`}><div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-600 to-purple-600 flex items-center justify-center text-white text-[11px] font-bold">{isSignedIn?(userProfile.initials||'GU'):'GU'}</div>{expanded&&<div className="min-w-0 flex-1 text-left"><div className="flex items-center gap-1.5"><span className="text-xs font-semibold truncate">{isSignedIn?userProfile.name:'Guest User'}</span><span className="text-[9px] px-1.5 rounded bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">{isSignedIn?userProfile.plan:'Free'}</span></div><span className="text-[10px] text-neutral-400">{isSignedIn?'Personal workspace':'Sign in / Sign up'}</span></div>}{expanded&&<ChevronRight className="w-4 h-4 text-neutral-400"/>}</button>;
  return <>
    <div className={`hidden md:block ${isSidebarCollapsed?'w-16':'w-64'} shrink-0 h-screen`}/>
    <motion.aside onMouseEnter={()=>isSidebarCollapsed&&setHoverExpanded(true)} onMouseLeave={()=>setHoverExpanded(false)} animate={{width:expanded?256:64}} transition={{duration:.12}} className={`hidden md:flex fixed left-0 top-0 z-50 h-screen flex-col border-r overflow-hidden ${isLight?'bg-white border-slate-200':'bg-[#0B0E14] border-white/5'}`}>
      <div className={`shrink-0 p-3 border-b ${isLight?'border-slate-100':'border-white/5'}`}><div className="h-9 flex items-center justify-between mb-2"><button onClick={()=>nav('home')} className="flex items-center gap-2.5"><AngelLogo size={28} glow/><span className={expanded?'font-semibold':'sr-only'}>Angel</span></button><div className="flex items-center gap-1">{expanded&&<button onClick={()=>openCommandPalette('all')} className="p-1.5 rounded-lg text-neutral-400"><Search className="w-4 h-4"/></button>}<button onClick={toggleSidebar} className="p-1.5 rounded-lg text-neutral-400">{isSidebarCollapsed?<PanelLeftOpen className="w-4 h-4"/>:<PanelLeftClose className="w-4 h-4"/>}</button></div></div><button onClick={newChat} className={`w-full flex items-center ${expanded?'gap-2 px-3':'justify-center'} py-2 rounded-xl text-xs font-semibold ${isLight?'bg-slate-100 hover:bg-slate-200':'bg-[#141824] hover:bg-[#1b2030]'}`}><SquarePen className="w-4 h-4 text-indigo-500"/>{expanded&&'New Chat'}</button><button onClick={()=>openCommandPalette('all')} className={`mt-2 w-full flex items-center ${expanded?'gap-2 px-3':'justify-center'} py-2 rounded-xl text-xs text-neutral-400 ${isLight?'bg-slate-50':'bg-[#121622]'}`}><Search className="w-4 h-4"/>{expanded&&<><span className="flex-1 text-left">Search</span><WindowsShortcutBadge shortcut="K"/></>}</button><button onClick={()=>nav('home')} className={`mt-2 w-full flex items-center ${expanded?'gap-3 px-3':'justify-center'} py-2 rounded-xl text-xs font-medium ${activeTab==='home'?(isLight?'bg-indigo-50 text-indigo-700':'bg-[#151926] text-white'):(isLight?'text-slate-600 hover:bg-slate-100':'text-neutral-400 hover:bg-white/5')}`}><Home className="w-4 h-4 text-indigo-500"/>{expanded&&'Home'}</button></div>
      <div className="flex-1 min-h-0 overflow-y-auto overscroll-contain custom-scrollbar p-2"><div className="space-y-1">{tools.map(([id,label,Icon,tab])=><button key={id} onClick={()=>nav(tab)} className={`w-full flex items-center ${expanded?'gap-3 px-3':'justify-center'} py-2 rounded-xl text-xs font-medium ${activeTab===tab?(isLight?'bg-indigo-50 text-indigo-700':'bg-[#151926] text-white'):(isLight?'text-slate-600 hover:bg-slate-100':'text-neutral-400 hover:bg-white/5')}`}><Icon className="w-4 h-4 text-indigo-400"/>{expanded&&label}</button>)}<button onClick={()=>nav('more')} className={`w-full flex items-center ${expanded?'gap-3 px-3':'justify-center'} py-2 rounded-xl text-xs font-medium ${activeTab==='more'?(isLight?'bg-indigo-50 text-indigo-700':'bg-[#151926] text-white'):(isLight?'text-slate-600 hover:bg-slate-100':'text-neutral-400 hover:bg-white/5')}`}><MoreHorizontal className="w-4 h-4"/>{expanded&&'More'}</button></div>{expanded&&<div className="space-y-3 pt-3">{pinned.length>0&&<section><div className="px-2 mb-1 text-[10px] uppercase tracking-[.14em] font-semibold text-neutral-400">Pinned</div>{pinned.map(row)}</section>}{archived.length>0&&<section><div className="px-2 mb-1 text-[10px] uppercase tracking-[.14em] font-semibold text-neutral-400">Archived</div>{archived.map(row)}</section>}<section><div className="px-2 mb-1 text-[10px] uppercase tracking-[.14em] font-semibold text-neutral-400">Recent</div>{recent.length?recent.map(row):<div className="px-2 text-[10px] text-neutral-500">No recent chats</div>}</section></div>}</div>
      <div className={`shrink-0 p-2.5 border-t ${isLight?'border-slate-100':'border-white/5'}`}>{expanded&&<div className={`mb-2 p-3 rounded-xl ${isLight?'bg-slate-50':'bg-[#121620]'}`}><div className="flex gap-2"><Quote className="w-3.5 h-3.5 text-indigo-400"/><span className="text-[10px] italic text-neutral-400">Small steps every day create big results.</span></div></div>}{profile}</div>
    </motion.aside>
    {isMobileMenuOpen&&<div className="fixed inset-0 z-[60] md:hidden"><div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={()=>setMobileMenuOpen(false)}/><aside className={`absolute left-0 top-0 bottom-0 w-72 p-3 flex flex-col shadow-2xl ${isLight?'bg-white':'bg-[#0B0E14]'}`}><div className="flex items-center justify-between h-10"><button onClick={()=>nav('home')} className="flex items-center gap-2"><AngelLogo size={28} glow/><span className="font-semibold">Angel</span></button><button onClick={()=>setMobileMenuOpen(false)}><X className="w-5 h-5"/></button></div><button onClick={newChat} className="mt-3 w-full flex items-center justify-center gap-2 py-2 rounded-xl bg-indigo-600 text-white text-xs font-semibold"><SquarePen className="w-4 h-4"/>New Chat</button><button onClick={()=>{setMobileMenuOpen(false);openCommandPalette('all')}} className="mt-2 w-full flex items-center gap-2 px-3 py-2 rounded-xl bg-black/5 dark:bg-white/5 text-xs text-neutral-400"><Search className="w-4 h-4"/>Search</button><button onClick={()=>nav('home')} className="mt-2 w-full flex items-center gap-3 px-3 py-2 rounded-xl text-xs"><Home className="w-4 h-4 text-indigo-500"/>Home</button><div className="flex-1 overflow-y-auto custom-scrollbar mt-2 space-y-1">{tools.map(([id,label,Icon,tab])=><button key={id} onClick={()=>nav(tab)} className="w-full flex items-center gap-3 px-3 py-2 rounded-xl text-xs text-neutral-400"><Icon className="w-4 h-4 text-indigo-400"/>{label}</button>)}<button onClick={()=>nav('more')} className="w-full flex items-center gap-3 px-3 py-2 rounded-xl text-xs text-neutral-400"><MoreHorizontal className="w-4 h-4"/>More</button>{pinned.map(row)}{archived.map(row)}{recent.map(row)}</div><div className="pt-2 border-t border-black/5 dark:border-white/5">{profile}</div></aside></div>}
    <UserProfileMenu isOpen={profileOpen} onClose={()=>setProfileOpen(false)}/>{chatOptionsId&&<ChatOptionsMenu conversationId={chatOptionsId} isOpen anchorPosition={chatAnchor} onClose={()=>setChatOptionsId(null)} onOpenSecrets={()=>setSecretsOpen(true)}/>}<SecretsModal isOpen={secretsOpen} onClose={()=>setSecretsOpen(false)}/>
  </>;
};
